const data = [
  {
    title: "Vibrant Graffiti",
    description: "A colorful graffiti wall.",
    location: "Downtown",
    artist_name: "John Doe",
    date_created: new Date("2023-05-15"),
    image_url: "https://example.com/image1.jpg",
  },
  {
    title: "Sunset Mural",
    description: "A mural depicting a beautiful sunset.",
    location: "Beachside",
    artist_name: "Jane Smith",
    date_created: new Date("2023-06-10"),
    image_url: "https://example.com/image2.jpg",
  },
  {
    title: "Abstract Chaos",
    description: "Abstract shapes and colors colliding.",
    location: "Art District",
    artist_name: "Alex Brown",
    date_created: new Date("2023-07-20"),
    image_url: "https://example.com/image3.jpg",
  },
  {
    title: "City Streets",
    description: "Graffiti inspired by the city's hustle.",
    location: "Uptown",
    artist_name: "Chris Green",
    date_created: new Date("2023-08-01"),
    image_url: "https://example.com/image4.jpg",
  },
  {
    title: "Serene Calligraphy",
    description: "Elegant calligraphy on a city wall.",
    location: "Old Town",
    artist_name: "Sarah Lee",
    date_created: new Date("2023-09-12"),
    image_url: "https://example.com/image5.jpg",
  },
  {
    title: "Pop Art Explosion",
    description: "Bright pop art style work.",
    location: "Mall Entrance",
    artist_name: "Daniel White",
    date_created: new Date("2023-10-05"),
    image_url: "https://example.com/image6.jpg",
  },
  {
    title: "Nature's Beauty",
    description: "A mural of nature scenes.",
    location: "Green Park",
    artist_name: "Mia Williams",
    date_created: new Date("2023-11-15"),
    image_url: "https://example.com/image7.jpg",
  },
  {
    title: "Urban Street Style",
    description: "A street style mural with bold colors.",
    location: "East Side",
    artist_name: "Ethan Black",
    date_created: new Date("2023-12-10"),
    image_url: "https://example.com/image8.jpg",
  },
  {
    title: "The Silent Poet",
    description: "A subtle piece of stencil art.",
    location: "Library Wall",
    artist_name: "Emily Johnson",
    date_created: new Date("2023-01-05"),
    image_url: "https://example.com/image9.jpg",
  },
  {
    title: "Flying High",
    description: "A mural with soaring birds.",
    location: "City Center",
    artist_name: "Olivia White",
    date_created: new Date("2023-02-18"),
    image_url: "https://example.com/image10.jpg",
  },
  {
    title: "Hidden Message",
    description: "A graffiti wall with a hidden message.",
    location: "Alleyway",
    artist_name: "Benjamin Turner",
    date_created: new Date("2023-03-25"),
    image_url: "https://example.com/image11.jpg",
  },
  {
    title: "Ocean Vibes",
    description: "A colorful ocean-themed mural.",
    location: "Pier",
    artist_name: "Lucas Carter",
    date_created: new Date("2023-04-07"),
    image_url: "https://example.com/image12.jpg",
  },
  {
    title: "Cosmic Journey",
    description: "A galaxy-themed mural.",
    location: "Museum District",
    artist_name: "Sophia Adams",
    date_created: new Date("2023-05-12"),
    image_url: "https://example.com/image13.jpg",
  },
  {
    title: "The Tiger",
    description: "A fierce tiger drawn in street art style.",
    location: "Zoo Road",
    artist_name: "Charlotte King",
    date_created: new Date("2023-06-22"),
    image_url: "https://example.com/image14.jpg",
  },
  {
    title: "Street Rhythm",
    description: "A graffiti tribute to music and rhythm.",
    location: "Downtown",
    artist_name: "James Scott",
    date_created: new Date("2023-07-09"),
    image_url: "https://example.com/image15.jpg",
  },
  {
    title: "Modern Abstract",
    description: "A mix of modern abstract art.",
    location: "Art Street",
    artist_name: "Daniel Harris",
    date_created: new Date("2023-08-25"),
    image_url: "https://example.com/image16.jpg",
  },
  {
    title: "Life in Color",
    description: "A mural celebrating life in color.",
    location: "Main Square",
    artist_name: "Ava Brown",
    date_created: new Date("2023-09-17"),
    image_url: "https://example.com/image17.jpg",
  },
  {
    title: "Love and Peace",
    description: "Graffiti symbolizing love and peace.",
    location: "Peace Park",
    artist_name: "Henry Lee",
    date_created: new Date("2023-10-01"),
    image_url: "https://example.com/image18.jpg",
  },
  {
    title: "Concrete Jungle",
    description: "A vibrant depiction of the city life.",
    location: "City Plaza",
    artist_name: "George Thomas",
    date_created: new Date("2023-11-14"),
    image_url: "https://example.com/image19.jpg",
  },
  {
    title: "Vintage Cars",
    description: "A retro street art of classic cars.",
    location: "Garage Road",
    artist_name: "Nina Davis",
    date_created: new Date("2023-12-22"),
    image_url: "https://example.com/image20.jpg",
  },
  {
    title: "Dreams in the Sky",
    description: "A mural of dreamlike clouds.",
    location: "Skyline View",
    artist_name: "Oliver White",
    date_created: new Date("2023-01-10"),
    image_url: "https://example.com/image21.jpg",
  },
  {
    title: "Shadow Play",
    description: "A street art piece using shadows.",
    location: "Back Alley",
    artist_name: "Rachel Hall",
    date_created: new Date("2023-02-28"),
    image_url: "https://example.com/image22.jpg",
  },
  {
    title: "Electric Waves",
    description: "A mural that captures energy in waves.",
    location: "Tech Park",
    artist_name: "Jack Wilson",
    date_created: new Date("2023-03-19"),
    image_url: "https://example.com/image23.jpg",
  },
  {
    title: "Nature's Whisper",
    description: "A subtle art piece blending nature.",
    location: "Forest Park",
    artist_name: "Sophia Clark",
    date_created: new Date("2023-04-30"),
    image_url: "https://example.com/image24.jpg",
  },
  {
    title: "Industrial Chic",
    description: "Graffiti blending industry and art.",
    location: "Factory Road",
    artist_name: "William Young",
    date_created: new Date("2023-05-24"),
    image_url: "https://example.com/image25.jpg",
  },
  {
    title: "Colorful Escape",
    description: "Bright colors capturing freedom.",
    location: "Subway Station",
    artist_name: "Ella Martin",
    date_created: new Date("2023-06-10"),
    image_url: "https://example.com/image26.jpg",
  },
  {
    title: "Whimsical Wonderland",
    description: "A fantasy-themed mural.",
    location: "Theme Park",
    artist_name: "Liam Carter",
    date_created: new Date("2023-07-03"),
    image_url: "https://example.com/image27.jpg",
  },
  {
    title: "The Phoenix",
    description: "A fiery mural of the mythical phoenix.",
    location: "Phoenix Road",
    artist_name: "Emma Turner",
    date_created: new Date("2023-08-14"),
    image_url: "https://example.com/image28.jpg",
  },
  {
    title: "Urban Jungle",
    description: "A colorful mix of animals and plants.",
    location: "Green District",
    artist_name: "Jacob Miller",
    date_created: new Date("2023-09-02"),
    image_url: "https://example.com/image29.jpg",
  },
  {
    title: "The Dreamer",
    description: "A mural of a person lost in thought.",
    location: "Parkside",
    artist_name: "Lily Baker",
    date_created: new Date("2023-10-19"),
    image_url: "https://example.com/image30.jpg",
  },
  {
    title: "The Night Sky",
    description: "A mural of stars and galaxies.",
    location: "City Skyline",
    artist_name: "Ethan Gray",
    date_created: new Date("2023-11-05"),
    image_url: "https://example.com/image31.jpg",
  },
  {
    title: "Flying Birds",
    description: "A vivid street art of birds in flight.",
    location: "Airport Road",
    artist_name: "Charlotte Evans",
    date_created: new Date("2023-12-14"),
    image_url: "https://example.com/image32.jpg",
  },
  {
    title: "Blazing Sunset",
    description: "A mural of a dramatic sunset.",
    location: "Seaside",
    artist_name: "Amelia Fisher",
    date_created: new Date("2024-01-03"),
    image_url: "https://example.com/image33.jpg",
  },
  {
    title: "City of Dreams",
    description: "A cityscape inspired mural.",
    location: "Downtown",
    artist_name: "Olivia Harris",
    date_created: new Date("2024-02-22"),
    image_url: "https://example.com/image34.jpg",
  },
  {
    title: "Art of Motion",
    description: "A dynamic graffiti piece.",
    location: "Highway Wall",
    artist_name: "Benjamin Moore",
    date_created: new Date("2024-03-01"),
    image_url: "https://example.com/image35.jpg",
  },
  {
    title: "Cultural Roots",
    description: "A tribute to diverse cultures.",
    location: "Cultural Square",
    artist_name: "Grace Allen",
    date_created: new Date("2024-04-10"),
    image_url: "https://example.com/image36.jpg",
  },
  {
    title: "Wild Life",
    description: "Street art of animals in their habitat.",
    location: "Zoo Street",
    artist_name: "Henry Davis",
    date_created: new Date("2024-05-20"),
    image_url: "https://example.com/image37.jpg",
  },
  {
    title: "Harmonic Balance",
    description: "A mural representing balance and harmony.",
    location: "Balance Park",
    artist_name: "Lily King",
    date_created: new Date("2024-06-05"),
    image_url: "https://example.com/image38.jpg",
  },
  {
    title: "Dancing Shapes",
    description: "A visual dance of geometric shapes.",
    location: "Tech District",
    artist_name: "Liam Adams",
    date_created: new Date("2024-07-15"),
    image_url: "https://example.com/image39.jpg",
  },
  {
    title: "The Secret Garden",
    description: "A mystical street art of a garden.",
    location: "Secret Alley",
    artist_name: "Sophia Mitchell",
    date_created: new Date("2024-08-03"),
    image_url: "https://example.com/image40.jpg",
  },
  {
    title: "Giant Waves",
    description: "A massive street art piece of ocean waves.",
    location: "Seafront",
    artist_name: "Jackson Harris",
    date_created: new Date("2024-09-11"),
    image_url: "https://example.com/image41.jpg",
  },
  {
    title: "Giant Waves",
    description: "A massive street art piece of ocean waves.",
    location: "Seafront",
    artist_name: "Jackson Harris",
    date_created: new Date("2024-09-11"),
    image_url: "https://example.com/image41.jpg",
  },
  {
    title: "Beneath the Stars",
    description: "A serene mural of a night sky.",
    location: "Mountain View",
    artist_name: "Isabella Lee",
    date_created: new Date("2024-10-01"),
    image_url: "https://example.com/image42.jpg",
  },
  {
    title: "Vivid Streets",
    description: "A vibrant mural capturing the energy of the city.",
    location: "City Center",
    artist_name: "Mason Clark",
    date_created: new Date("2024-10-15"),
    image_url: "https://example.com/image43.jpg",
  },
  {
    title: "Future Visions",
    description: "A futuristic design of a cityscape.",
    location: "Tech Park",
    artist_name: "Aiden Wright",
    date_created: new Date("2024-11-03"),
    image_url: "https://example.com/image44.jpg",
  },
  {
    title: "Fallen Angels",
    description: "A piece with angels depicted in graffiti style.",
    location: "Old Warehouse",
    artist_name: "Mia Young",
    date_created: new Date("2024-11-18"),
    image_url: "https://example.com/image45.jpg",
  },
  {
    title: "Floating Hearts",
    description: "Graffiti with hearts in the sky.",
    location: "Park Road",
    artist_name: "Liam Scott",
    date_created: new Date("2024-12-01"),
    image_url: "https://example.com/image46.jpg",
  },
  {
    title: "Electric Street",
    description: "A street art capturing the electric vibe of nightlife.",
    location: "Night District",
    artist_name: "Chloe Turner",
    date_created: new Date("2024-12-22"),
    image_url: "https://example.com/image47.jpg",
  },
  {
    title: "Peaceful Garden",
    description: "A mural showcasing peaceful garden scenes.",
    location: "Zen Park",
    artist_name: "Noah Evans",
    date_created: new Date("2025-01-07"),
    image_url: "https://example.com/image48.jpg",
  },
  {
    title: "Rhythmic Shapes",
    description: "An abstract artwork symbolizing rhythm and flow.",
    location: "Dance Hall",
    artist_name: "Sophie Harris",
    date_created: new Date("2025-01-20"),
    image_url: "https://example.com/image49.jpg",
  },
  {
    title: "Echoes of the Past",
    description: "A street art piece that reflects historical elements.",
    location: "Museum District",
    artist_name: "Ethan Martin",
    date_created: new Date("2025-02-05"),
    image_url: "https://example.com/image50.jpg",
  },
];

module.exports=data;